# name of the workflow
name: Test workflow
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  #job1 
  test:
    
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: trying to check the tests
        run: echo Hello,World!
# job2
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://www.jumia.co.ke/"

#  auto merge job
  merge:
    name: Reviewing and merging PR
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'zachydev' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Merging PR
      run: Merged PR 

