# this is the workflow name
name: basic test workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This workflow consists of a single job called test
jobs:
  test:
    name: Running Unit Test1
    # the type of runner it will run on
    runs-on: ubuntu-latest

    # steps
    steps:
      - uses: actions/checkout@v2
      - name: run one line script
        run: echo Hello,World!

      - name: run a multi-line script
        run: |
            echo Add your projects to test
            echo deploy and test the application



