# name of the workflow
name: Test workflow
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  test:
    
    name: Running the test file
    runs-on: windows-latest
    steps:
      - uses: action/checkout@v2
      - name: trying to check the tests
        run: echo Hello,World!
        
    
