# name of the workflow
name: Test workflow
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  #job1 
  test:
    
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          dev: ${{secret.DEVLOPER_NAME}}  
      - name: trying to check the tests
        run: echo Hello,World! from dev
# job2
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://www.jumia.co.ke/"
    
